# Generated by Django 3.1 on 2022-03-14 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolBoxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='全名')),
                ('nickName', models.CharField(blank=True, default='', max_length=10, verbose_name='暱稱')),
                ('selfIntro', models.TextField(blank=True, default='', verbose_name='自我介紹')),
                ('takeTaskPermission', models.BooleanField(blank=True, default=True, verbose_name='可否應徵當工具人')),
                ('uploadTaskPermission', models.BooleanField(blank=True, default=True, verbose_name='可否發布委託')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toolboxAccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工具人帳號',
            },
        ),
    ]
