# Generated by Django 3.1 on 2022-03-23 16:35

from django.db import migrations, models
import toolfamily.models


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.PositiveBigIntegerField(default=toolfamily.models.IntUUID, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='casephoto',
            name='casephoto_id',
            field=models.PositiveBigIntegerField(default=toolfamily.models.IntUUID, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='casewillingness',
            name='casewillingness_id',
            field=models.PositiveBigIntegerField(default=toolfamily.models.IntUUID, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='commissionrecord_id',
            field=models.PositiveBigIntegerField(default=toolfamily.models.IntUUID, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followcase',
            name='followcase_id',
            field=models.PositiveBigIntegerField(default=toolfamily.models.IntUUID, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='followuser_id',
            field=models.PositiveBigIntegerField(default=toolfamily.models.IntUUID, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.PositiveBigIntegerField(default=toolfamily.models.IntUUID, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_id',
            field=models.PositiveBigIntegerField(default=toolfamily.models.IntUUID, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userreportedrecord',
            name='record_id',
            field=models.PositiveBigIntegerField(default=toolfamily.models.IntUUID, editable=False, primary_key=True, serialize=False),
        ),
    ]
