# Generated by Django 3.1 on 2022-03-23 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='ended_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 12, 39, 10, 165819, tzinfo=utc), verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='casephoto',
            name='image',
            field=models.ImageField(upload_to='images/casePhoto/'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/userIcon/'),
        ),
    ]
