# Generated by Django 4.0.3 on 2022-04-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='num',
            field=models.IntegerField(default=1, verbose_name='徵求人數'),
        ),
        migrations.AddField(
            model_name='case',
            name='work',
            field=models.IntegerField(blank=True, default=None, help_text='0:實體, 1:線上, 留空:無偏好', null=True, verbose_name='偏好的工作方式'),
        ),
    ]
