# Generated by Django 3.1 on 2022-03-16 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='標題')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('reward', models.CharField(blank=True, default='', max_length=30, verbose_name='報酬')),
                ('location', models.CharField(blank=True, default='', max_length=50, verbose_name='地點')),
                ('solution', models.CharField(blank=True, default='', max_length=50, verbose_name='解決方法')),
                ('limitation', models.CharField(blank=True, default='', max_length=50, verbose_name='限制條件')),
                ('startTime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='開始時間')),
                ('endTime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='結束時間')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='發布時間')),
                ('assignAt', models.DateTimeField(blank=True, default=None, help_text='委託人確定給哪些工具人做的時間點', null=True, verbose_name='成案時間')),
                ('finishAt', models.DateTimeField(blank=True, default=None, help_text='工具人按下確定的時間點', null=True, verbose_name='完成時間')),
                ('doubleCheckFinishAt', models.DateTimeField(blank=True, default=None, help_text='委託人按下確定的時間點', null=True, verbose_name='雙重確認-完成時間')),
                ('lastChange', models.DateTimeField(auto_now=True, verbose_name='最後修改')),
            ],
            options={
                'verbose_name': '委託單',
            },
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=10, verbose_name='狀態名稱')),
                ('description', models.CharField(default='', max_length=30, verbose_name='說明')),
            ],
            options={
                'verbose_name': '委託單狀態',
            },
        ),
        migrations.AlterModelOptions(
            name='toolboxuser',
            options={'verbose_name': '帳號'},
        ),
        migrations.AddField(
            model_name='toolboxuser',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolboxuser',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='啟用狀態'),
        ),
        migrations.AlterField(
            model_name='toolboxuser',
            name='takeTaskPermission',
            field=models.BooleanField(default=True, verbose_name='可否應徵當工具人'),
        ),
        migrations.AlterField(
            model_name='toolboxuser',
            name='uploadTaskPermission',
            field=models.BooleanField(default=True, verbose_name='可否發布委託'),
        ),
        migrations.CreateModel(
            name='TaskApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='附加資訊')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('isAccept', models.BooleanField(default=False, help_text='當委託人決定委託這人，設為 True', verbose_name='確認接案')),
                ('isCancel', models.BooleanField(default=False, help_text='若應徵者後來要取消，設為 True；可供計算取消次數', verbose_name='應徵者取消')),
                ('applyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applys', to='toolfamily.toolboxuser', verbose_name='應徵者')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applys', to='toolfamily.task', verbose_name='委託單')),
            ],
            options={
                'verbose_name': '應徵資訊',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='toolfamily.toolboxuser', verbose_name='委託人'),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='toolfamily.taskstate', verbose_name='狀態'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('reportOnTask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beReported', to='toolfamily.task', verbose_name='被檢舉的委託單')),
                ('reportOnUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beReported', to='toolfamily.toolboxuser', verbose_name='被檢舉人')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='toolfamily.toolboxuser', verbose_name='檢舉人')),
            ],
            options={
                'verbose_name': '檢舉',
            },
        ),
    ]
