# Generated by Django 4.0.3 on 2022-03-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='last_login_datetime',
            field=models.DateTimeField(default=None, verbose_name='上次登入時間'),
        ),
    ]
