# Generated by Django 4.0.3 on 2022-03-24 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0002_auto_20220323_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='ended_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 9, 49, 29, 433790, tzinfo=utc), verbose_name='結束時間'),
        ),
    ]
