# Generated by Django 3.1 on 2022-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0003_auto_20220324_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='rate',
            field=models.DecimalField(decimal_places=13, default=0, max_digits=15, verbose_name='評價'),
        ),
    ]
