# Generated by Django 4.0.3 on 2022-04-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0002_case_num_case_work'),
        ('toolfamily', '0004_auto_20220405_0048'),
    ]

    operations = [
    ]
