# Generated by Django 3.1 on 2022-03-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0004_auto_20220324_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='report_type_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
