# Generated by Django 4.0.3 on 2022-04-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0005_alter_userdetail_last_login_datetime'),
        ('toolfamily', '0005_merge_0002_case_num_case_work_0004_auto_20220405_0048'),
    ]

    operations = [
    ]
