# Generated by Django 3.1 on 2022-04-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0006_merge_20220407_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='contactInfo',
            field=models.TextField(blank=True, default='', verbose_name='聯絡資訊'),
        ),
    ]
