# Generated by Django 4.0.3 on 2022-04-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0006_merge_20220407_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, default='', verbose_name='通知內容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_user', to='toolfamily.userdetail', verbose_name='通知使用者')),
            ],
        ),
    ]
