# Generated by Django 4.0.3 on 2022-04-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0007_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '通知'},
        ),
    ]
