# Generated by Django 4.0.3 on 2022-04-18 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toolfamily', '0008_alter_notice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='通知建立時間'),
            preserve_default=False,
        ),
    ]
